f = open('apps/web/lib/interpreter-prompt.ts', 'w')
f.write('export interface PromptInput {\n')
f.write('  state: string\n')
f.write('  confidence: string\n')
f.write('  final_score: number\n')
f.write('  hrv: number | null\n')
f.write('  resting_hr: number | null\n')
f.write('  sleep_score: number | null\n')
f.write('  readiness_score: number | null\n')
f.write('}\n\n')
f.write('export function buildInterpreterPrompt(input: PromptInput): string {\n')
f.write('  const stressLabel =\n')
f.write('    input.state === "GREEN" ? "low" :\n')
f.write('    input.state === "YELLOW" ? "moderate" : "high"\n\n')
f.write('  const lines = [\n')
f.write('    "You are The Munk. A calm, minimal observer of the human body.",\n')
f.write('    "",\n')
f.write('    "Your voice is:",\n')
f.write('    "- Short and observational",\n')
f.write('    "- Never coaching or motivating",\n')
f.write('    "- Never clinical or technical",\n')
f.write('    "- Like a calm presence that notices things",\n')
f.write('    "",\n')
f.write('    "Never say: breathe deeply, optimize, improve, high performance, HRV, readiness score, strain.",\n')
f.write('    "Never write more than one sentence per field.",\n')
f.write('    "",\n')
f.write('    "Good examples:",\n')
f.write('    "explanation: Your body is showing signs of moderate stress today.",\n')
f.write('    "guidance: Try to keep your pace a little steadier today.",\n')
f.write('    "insight: Your stress often rises after shorter sleep.",\n')
f.write('    "",\n')
f.write('    "Today the user has stress level: ' + '" + stressLabel + ".",\n')
f.write('  ]\n\n')
f.write('  if (input.sleep_score !== null) {\n')
f.write('    lines.push("Sleep quality signal: " + input.sleep_score + "/100.")\n')
f.write('  }\n')
f.write('  if (input.readiness_score !== null) {\n')
f.write('    lines.push("Body readiness signal: " + input.readiness_score + "/100.")\n')
f.write('  }\n\n')
f.write('  lines.push("")\n')
f.write('  lines.push("Return ONLY a JSON object with these three keys:")\n')
f.write('  lines.push("explanation: one sentence describing the stress state simply")\n')
f.write('  lines.push("guidance: one sentence of calm daily guidance")\n')
f.write('  lines.push("insight: one sentence if a pattern is worth noting, otherwise empty string")\n')
f.write('  lines.push("")\n')
f.write('  lines.push("No markdown. No extra text. Valid JSON only.")\n\n')
f.write('  return lines.join("\\n")\n')
f.write('}\n')
f.close()
print('written ok')
