import os
os.makedirs('docs/architecture', exist_ok=True)
f = open('docs/architecture/PIPELINE_BASELINE.md', 'w')
f.write('# The Munk - Pipeline Baseline and Debug Protocol\n\n')
f.write('## Canonical Pipeline\n\n')
f.write('Oura -> OuraAdapter -> wearable_logs -> computeStateV2 -> daily_state -> /api/state/today -> DecisionContract -> Daily Brief UI\n\n')
f.write('## Operational Status (baseline: 2026-03-15)\n\n')
f.write('- Oura sync: operational\n')
f.write('- wearable_logs persistence: operational\n')
f.write('- computeStateV2: operational\n')
f.write('- daily_state persistence: operational\n')
f.write('- /api/state/today: operational\n')
f.write('- Daily Brief UI: operational\n\n')
f.write('## MVP Real-Data Baseline\n\n')
f.write('Reference user: Thomas Holm (user_id: thomas)\n')
f.write('Reference wearable: Oura Ring\n')
f.write('Primary signals: HRV, resting HR, sleep score, readiness score\n\n')
f.write('NOTE: This is the MVP reference dataset only.\n')
f.write('Thomas/Oura is the reference baseline, not the permanent global user model.\n')
f.write('Do not treat hardcoded user_id thomas as a universal assumption.\n\n')
f.write('## Debug Order\n\n')
f.write('When something fails, debug in this exact order:\n\n')
f.write('1. Data in - did Oura sync run? Check wearable_logs\n')
f.write('2. State compute - did computeStateV2 run? Check daily_state\n')
f.write('3. Persistence - does daily_state have a row for today?\n')
f.write('4. Endpoint - does /api/state/today return 200?\n')
f.write('5. UI - only investigate frontend after all above are confirmed\n\n')
f.write('Do not start with UX or design before pipeline is verified.\n\n')
f.write('## Safeguards\n\n')
f.write('- sync self-verify: sync/route.ts reads back daily_state after upsert, returns 500 if missing\n')
f.write('- smoke endpoint: /api/system/smoke checks all four pipeline layers\n')
f.write('- health endpoint: /api/system/health uses service role, reports pipeline_ok and today_state_present\n\n')
f.write('## Architecture Rules\n\n')
f.write('- daily_state is canonical state storage, never recompute in product routes\n')
f.write('- LLMs generate language only, never determine physiological state\n')
f.write('- All stateful routes: force-dynamic + Cache-Control: no-store\n')
f.write('- Service role key required for oura_tokens and daily_state access\n')
f.write('- Oslo timezone (Europe/Oslo) for all day_key calculations\n')
f.close()
print('written ok')
