import os
os.makedirs('apps/web/app/api/interpreter/today', exist_ok=True)
f = open('apps/web/app/api/interpreter/today/route.ts', 'w')
f.write('export const dynamic = "force-dynamic"\n')
f.write('export const revalidate = 0\n\n')
f.write('import { NextResponse } from "next/server"\n')
f.write('import { createClient } from "@supabase/supabase-js"\n')
f.write('import { callOpenAI } from "../../../../lib/openai-provider"\n')
f.write('import { buildInterpreterPrompt } from "../../../../lib/interpreter-prompt"\n')
f.write('import { guidanceEngineV1 } from "@themunk/core/state/guidance-engine"\n')
f.write('import { patternEngineV1 } from "@themunk/core/state/pattern-engine-v1"\n\n')
f.write('function getServiceClient() {\n')
f.write('  return createClient(\n')
f.write('    process.env.NEXT_PUBLIC_SUPABASE_URL!,\n')
f.write('    process.env.SUPABASE_SERVICE_ROLE_KEY!\n')
f.write('  )\n')
f.write('}\n\n')
f.write('function todayOslo(): string {\n')
f.write('  return new Intl.DateTimeFormat("sv-SE", {\n')
f.write('    timeZone: "Europe/Oslo",\n')
f.write('  }).format(new Date())\n')
f.write('}\n\n')
f.write('export async function GET() {\n')
f.write('  const supabase = getServiceClient()\n')
f.write('  const dayKey = todayOslo()\n\n')
f.write('  // Get today state\n')
f.write('  const { data, error } = await supabase\n')
f.write('    .from("daily_state")\n')
f.write('    .select("state, confidence, final_score, sleep_score, recovery_score, hrv, rhr")\n')
f.write('    .eq("user_id", "thomas")\n')
f.write('    .eq("day_key", dayKey)\n')
f.write('    .maybeSingle()\n\n')
f.write('  if (error || !data) {\n')
f.write('    return NextResponse.json(\n')
f.write('      { error: "No state available for today" },\n')
f.write('      { status: 404, headers: { "Cache-Control": "no-store" } }\n')
f.write('    )\n')
f.write('  }\n\n')
f.write('  const state = data.state as "GREEN" | "YELLOW" | "RED"\n\n')
f.write('  // Get last 5 days of states for pattern detection\n')
f.write('  const { data: recentRows } = await supabase\n')
f.write('    .from("daily_state")\n')
f.write('    .select("state, day_key")\n')
f.write('    .eq("user_id", "thomas")\n')
f.write('    .order("day_key", { ascending: false })\n')
f.write('    .limit(5)\n\n')
f.write('  const recentStates = (recentRows ?? []).map((r: { state: string }) => r.state)\n\n')
f.write('  // Run pattern engine\n')
f.write('  const pattern = patternEngineV1({\n')
f.write('    state,\n')
f.write('    sleep_score: data.sleep_score ?? null,\n')
f.write('    recent_states: recentStates,\n')
f.write('    context_tags: [],\n')
f.write('  })\n\n')
f.write('  // Build AI prompt\n')
f.write('  const prompt = buildInterpreterPrompt({\n')
f.write('    state,\n')
f.write('    confidence: data.confidence,\n')
f.write('    final_score: data.final_score,\n')
f.write('    hrv: data.hrv ?? null,\n')
f.write('    resting_hr: data.rhr ?? null,\n')
f.write('    sleep_score: data.sleep_score ?? null,\n')
f.write('    readiness_score: data.recovery_score ?? null,\n')
f.write('  })\n\n')
f.write('  const aiResult = await callOpenAI(prompt)\n\n')
f.write('  // Use pattern insight if detected, otherwise empty\n')
f.write('  const insight = pattern.pattern_detected ? pattern.insight : ""\n\n')
f.write('  if (aiResult) {\n')
f.write('    return NextResponse.json(\n')
f.write('      {\n')
f.write('        explanation: aiResult.explanation,\n')
f.write('        guidance: aiResult.guidance,\n')
f.write('        insight,\n')
f.write('        pattern_id: pattern.pattern_id ?? null,\n')
f.write('        source: "ai",\n')
f.write('        state,\n')
f.write('        day_key: dayKey,\n')
f.write('      },\n')
f.write('      { headers: { "Cache-Control": "no-store" } }\n')
f.write('    )\n')
f.write('  }\n\n')
f.write('  // Fallback\n')
f.write('  const fallback = guidanceEngineV1(state)\n')
f.write('  const stressLabel = state === "GREEN" ? "low" : state === "YELLOW" ? "moderate" : "high"\n\n')
f.write('  return NextResponse.json(\n')
f.write('    {\n')
f.write('      explanation: "Your stress level is " + stressLabel + " today.",\n')
f.write('      guidance: fallback.body,\n')
f.write('      insight,\n')
f.write('      pattern_id: pattern.pattern_id ?? null,\n')
f.write('      source: "fallback",\n')
f.write('      state,\n')
f.write('      day_key: dayKey,\n')
f.write('    },\n')
f.write('    { headers: { "Cache-Control": "no-store" } }\n')
f.write('  )\n')
f.write('}\n')
f.close()
print('written ok')
