f = open('docs/architecture/AI_LEARNING_LOG.md', 'w')
f.write('# THE MUNK - AI Learning Log\n\n')
f.write('This file documents significant system mistakes and lessons.\n')
f.write('Updated only for pipeline failures, AI output problems, external API failures, or architecture mistakes.\n\n')
f.write('---\n\n')
f.write('## Date\n')
f.write('2026-03-15\n\n')
f.write('## Mistake\n')
f.write('Daily Brief showed "Could not load today\'s forecast" every morning.\n\n')
f.write('## Cause\n')
f.write('sync/route.ts wrote to wearable_logs but never called computeStateV2 or wrote to daily_state.\n')
f.write('Cron ran sync daily, but daily_state remained empty.\n')
f.write('/api/state/today returned 404 because no row existed for today.\n\n')
f.write('## Lesson\n')
f.write('A route can appear healthy (status: ok) while silently failing to complete the pipeline.\n')
f.write('Sync success does not mean state persistence success.\n\n')
f.write('## Prevention\n')
f.write('1. sync/route.ts now calls computeStateV2 and writes to daily_state after wearable_logs upsert.\n')
f.write('2. sync self-verify: reads back daily_state row after upsert, returns 500 if missing.\n')
f.write('3. /api/system/smoke verifies all four pipeline layers on demand.\n')
f.write('4. /api/system/health uses service role and reports pipeline_ok and today_state_present.\n')
f.write('5. Debug order documented in PIPELINE_BASELINE.md: data in -> state compute -> persistence -> endpoint -> UI.\n\n')
f.write('---\n\n')
f.write('## Date\n')
f.write('2026-03-15\n\n')
f.write('## Mistake\n')
f.write('AI Interpreter returned wellness-coach language instead of The Munk voice.\n\n')
f.write('## Cause\n')
f.write('System prompt gave the model too much freedom.\n')
f.write('No explicit bad examples. Temperature too high (0.4).\n\n')
f.write('## Lesson\n')
f.write('LLMs default to generic wellness language without tight constraints.\n')
f.write('Tone must be enforced with explicit BAD and GOOD examples, not just descriptions.\n\n')
f.write('## Prevention\n')
f.write('1. System prompt now includes explicit BAD/GOOD examples.\n')
f.write('2. Temperature lowered to 0.3.\n')
f.write('3. Forbidden words listed directly in prompt.\n')
f.write('4. AI_PLAYBOOK.md documents voice rules as permanent system truth.\n\n')
f.write('---\n\n')
f.write('## Date\n')
f.write('2026-03-15\n\n')
f.write('## Mistake\n')
f.write('OPENAI_API_KEY appeared saved in Vercel but was empty (Sensitive flag issue).\n\n')
f.write('## Cause\n')
f.write('Sensitive environment variables in Vercel cannot be set for Development environment.\n')
f.write('Multiple save attempts via UI failed silently without clear error.\n\n')
f.write('## Lesson\n')
f.write('Sensitive API keys must be added via Vercel CLI (npx vercel env add) for reliable storage.\n')
f.write('UI-based entry for Sensitive vars is unreliable.\n\n')
f.write('## Prevention\n')
f.write('Use: npx vercel env add KEY_NAME production\n')
f.write('Verify with: /api/system/debug-env endpoint (shows has_key and key_length, never value).\n\n')
f.write('---\n')
f.close()
print('written ok')
