f = open('apps/web/lib/openai-provider.ts', 'w')
f.write('export interface AIInterpretation {\n')
f.write('  explanation: string\n')
f.write('  guidance: string\n')
f.write('  insight: string\n')
f.write('}\n\n')
f.write('export async function callOpenAI(prompt: string): Promise<AIInterpretation | null> {\n')
f.write('  const apiKey = process.env.OPENAI_API_KEY\n')
f.write('  if (!apiKey) {\n')
f.write('    console.error("[openai-provider] OPENAI_API_KEY missing")\n')
f.write('    return null\n')
f.write('  }\n\n')
f.write('  try {\n')
f.write('    const res = await fetch("https://api.openai.com/v1/chat/completions", {\n')
f.write('      method: "POST",\n')
f.write('      headers: {\n')
f.write('        "Content-Type": "application/json",\n')
f.write('        "Authorization": "Bearer " + apiKey,\n')
f.write('      },\n')
f.write('      body: JSON.stringify({\n')
f.write('        model: "gpt-4o-mini",\n')
f.write('        max_tokens: 200,\n')
f.write('        temperature: 0.4,\n')
f.write('        messages: [\n')
f.write('          { role: "system", content: "You are a calm health guide. Return only valid JSON with keys: explanation, guidance, insight. No markdown." },\n')
f.write('          { role: "user", content: prompt },\n')
f.write('        ],\n')
f.write('      }),\n')
f.write('    })\n\n')
f.write('    const responseText = await res.text()\n')
f.write('    console.log("[openai-provider] status:", res.status)\n')
f.write('    console.log("[openai-provider] response:", responseText.slice(0, 300))\n\n')
f.write('    if (!res.ok) {\n')
f.write('      console.error("[openai-provider] API error", res.status, responseText.slice(0, 200))\n')
f.write('      return null\n')
f.write('    }\n\n')
f.write('    const data = JSON.parse(responseText)\n')
f.write('    const raw = data.choices?.[0]?.message?.content ?? ""\n')
f.write('    console.log("[openai-provider] raw content:", raw)\n')
f.write('    const parsed: AIInterpretation = JSON.parse(raw)\n\n')
f.write('    if (!parsed.explanation || !parsed.guidance) return null\n\n')
f.write('    return {\n')
f.write('      explanation: parsed.explanation,\n')
f.write('      guidance: parsed.guidance,\n')
f.write('      insight: parsed.insight ?? "",\n')
f.write('    }\n')
f.write('  } catch (err) {\n')
f.write('    console.error("[openai-provider] exception:", err)\n')
f.write('    return null\n')
f.write('  }\n')
f.write('}\n')
f.close()
print('written ok')
