f = open('apps/web/app/api/system/smoke/route.ts', 'w')
f.write('export const dynamic = "force-dynamic"\n')
f.write('export const revalidate = 0\n\n')
f.write('import { NextResponse } from "next/server"\n')
f.write('import { createClient } from "@supabase/supabase-js"\n\n')
f.write('function getServiceClient() {\n')
f.write('  return createClient(\n')
f.write('    process.env.NEXT_PUBLIC_SUPABASE_URL!,\n')
f.write('    process.env.SUPABASE_SERVICE_ROLE_KEY!\n')
f.write('  )\n')
f.write('}\n\n')
f.write('function todayOslo(): string {\n')
f.write('  return new Intl.DateTimeFormat("sv-SE", {\n')
f.write('    timeZone: "Europe/Oslo",\n')
f.write('  }).format(new Date())\n')
f.write('}\n\n')
f.write('export async function GET() {\n')
f.write('  const supabase = getServiceClient()\n')
f.write('  const dayKey = todayOslo()\n')
f.write('  const checks: Record<string, boolean> = {}\n\n')
f.write('  const { data: wearable } = await supabase\n')
f.write('    .from("wearable_logs")\n')
f.write('    .select("day_key")\n')
f.write('    .eq("user_id", "thomas")\n')
f.write('    .eq("day_key", dayKey)\n')
f.write('    .maybeSingle()\n')
f.write('  checks.wearable_logs = !!wearable\n\n')
f.write('  const { data: state } = await supabase\n')
f.write('    .from("daily_state")\n')
f.write('    .select("state, confidence, final_score")\n')
f.write('    .eq("user_id", "thomas")\n')
f.write('    .eq("day_key", dayKey)\n')
f.write('    .maybeSingle()\n')
f.write('  checks.daily_state = !!state\n')
f.write('  checks.state_valid = !!state && ["GREEN", "YELLOW", "RED"].includes(state.state)\n\n')
f.write('  try {\n')
f.write('    const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://www.themunk.ai"\n')
f.write('    const res = await fetch(baseUrl + "/api/state/today")\n')
f.write('    checks.endpoint_ok = res.ok\n')
f.write('  } catch {\n')
f.write('    checks.endpoint_ok = false\n')
f.write('  }\n\n')
f.write('  // Check last sync event to distinguish pending vs failure\n')
f.write('  const { data: lastSync } = await supabase\n')
f.write('    .from("wearable_sync_events")\n')
f.write('    .select("success, created_at, error_code")\n')
f.write('    .eq("user_id", "thomas")\n')
f.write('    .eq("day_key", dayKey)\n')
f.write('    .order("created_at", { ascending: false })\n')
f.write('    .limit(1)\n')
f.write('    .maybeSingle()\n\n')
f.write('  const allPassing = Object.values(checks).every(Boolean)\n\n')
f.write('  // Determine if this is pending or a real failure\n')
f.write('  let pipelineStatus = "ok"\n')
f.write('  let todayDataReady = true\n')
f.write('  let pendingReason: string | null = null\n\n')
f.write('  if (!allPassing) {\n')
f.write('    if (lastSync?.success === false && lastSync?.error_code === "EXCEPTION") {\n')
f.write('      pipelineStatus = "failure"\n')
f.write('      todayDataReady = false\n')
f.write('      pendingReason = "pipeline_error"\n')
f.write('    } else if (!lastSync || lastSync?.error_code === null) {\n')
f.write('      pipelineStatus = "pending"\n')
f.write('      todayDataReady = false\n')
f.write('      pendingReason = "oura_data_pending"\n')
f.write('    } else {\n')
f.write('      pipelineStatus = "degraded"\n')
f.write('      todayDataReady = false\n')
f.write('      pendingReason = "unknown"\n')
f.write('    }\n')
f.write('  }\n\n')
f.write('  console.log("[smoke] pipeline check", { day_key: dayKey, checks, pipelineStatus })\n\n')
f.write('  return NextResponse.json(\n')
f.write('    {\n')
f.write('      status: pipelineStatus,\n')
f.write('      today_data_ready: todayDataReady,\n')
f.write('      pending_reason: pendingReason,\n')
f.write('      day_key: dayKey,\n')
f.write('      checks,\n')
f.write('      state: state ?? null,\n')
f.write('    },\n')
f.write('    {\n')
f.write('      status: pipelineStatus === "failure" ? 500 : 200,\n')
f.write('      headers: { "Cache-Control": "no-store" },\n')
f.write('    }\n')
f.write('  )\n')
f.write('}\n')
f.close()
print('written ok')
