// packages/core/index.ts
export * from "./types";
export { computeTrendReport } from "./trend/extractor";
export { classifyState, classifySignal } from "./state/classifier";
export { computeState } from "./state/pipeline";
export { computeIntervention } from "./state/intervention";
export { computePolicy } from "./policy/compute_policy";
export type { PolicyDecisions, DailyStateInput, ReadinessBand, GuidanceIntensity } from "./policy/compute_policy";
export { assembleBrief } from "./renderer/assemble_brief";
export type { DailyBrief } from "./renderer/assemble_brief";
export { selectTemplate } from "./renderer/select_template";
export { buildDisclaimer } from "./renderer/build_disclaimer";
export { gatekeep } from "./gatekeeper/decision";
export type { GatekeeperDecision } from "./gatekeeper/decision";
export { buildFallbackBrief } from "./gatekeeper/fallback_builder";
export { scanText } from "./gatekeeper/scan";
export { FallbackAdapter } from "./llm/llm_adapter";
export { LLMAdapter, } from "./llm/llm_adapter";
export type { SlotFillerInput, SlotFillerOutput } from "./llm/types";
export { fillWhatItMightMean } from "./renderer/slot_filler/fill_what_it_might_mean";
export type { LLMRequest, LLMResponse } from "./llm/types";
export * from './wearables';
